name: Deploy to VPS

on:
  push:
    branches:
      - main
      
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p 10320 -H marek320.mikrus.xyz >> ~/.ssh/known_hosts

      - name: Sync files to VPS
        run: |
          rsync -avz --delete -e "ssh -p 10320" ./ marek320@marek320.mikrus.xyz:/srv/nexus

